[package]
name = 'sample-cicd-rs'
version = '0.1.0'
edition = '2021'
authors = ['thinkgos <thinkgo@aliyun.com>']

[dependencies]
actix-web = '4'

[dependencies.tokio]
version = '1'
features = [
    'macros',
    'rt-multi-thread',
]
